import { AlertCircle, ArrowRight, CheckCircle2, CircleDot, FileCheck2, Filter, LockKeyhole, MessageSquareText, Scale, SearchCheck, ShieldCheck, SlidersHorizontal, Sparkles, Target, UsersRound } from "lucide-react";

type Mode = "search" | "properties" | "deals" | "sellers" | "buyers" | "contracts" | "settings";

function EvidencePanel({ title, description, children }: { title: string; description: string; children: React.ReactNode }) {
  return <section className="panel evidence-panel"><header className="panel-heading"><div><h2>{title}</h2><p>{description}</p></div></header>{children}</section>;
}
function StateRow({ label, value = "UNAVAILABLE IN STANDALONE PREVIEW", icon: Icon = CircleDot }: { label: string; value?: string; icon?: typeof CircleDot }) {
  return <div className="evidence-row"><span className="evidence-label"><Icon size={14} />{label}</span><span className="evidence-value">{value}</span></div>;
}
function EmptyEvidence({ title, description }: { title: string; description: string }) {
  return <div className="evidence-empty"><LockKeyhole size={18} /><strong>{title}</strong><span>{description}</span></div>;
}
function SectionStat({ label, value = "—", detail = "No verified record" }: { label: string; value?: string; detail?: string }) {
  return <div className="evidence-stat"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>;
}

function SearchDetails() {
  return <div className="evidence-grid"><EvidencePanel title="Result controls" description="Provider-backed pagination and investment-fit context."><div className="evidence-stats"><SectionStat label="Page" value="1 / 1" detail="No source pages loaded" /><SectionStat label="Results per page" value="50" detail="Approved performance target" /><SectionStat label="Investment fit" value="—" detail="Needs verified metrics" /></div><div className="evidence-row"><span className="evidence-label"><Filter size={14}/> Active criteria</span><span className="evidence-value">Location · price · type · equity · distress</span></div><div className="evidence-row"><span className="evidence-label"><SlidersHorizontal size={14}/> Sort</span><span className="evidence-value">Provider relevance · newest update</span></div></EvidencePanel><EvidencePanel title="Quick analysis indicators" description="Each card will retain its provider source and calculation classification."><div className="indicator-grid"><div><strong>Price vs. value</strong><span>UNKNOWN</span><small>Requires source price and estimated value</small></div><div><strong>Potential spread</strong><span>UNKNOWN</span><small>Requires deterministic analysis inputs</small></div><div><strong>Criteria fit</strong><span>UNKNOWN</span><small>Requires saved organization criteria</small></div></div><EmptyEvidence title="No verified property cards" description="Pagination and quick indicators remain empty until the approved property provider is enabled." /></EvidencePanel></div>;
}
function PropertyDetails() {
  return <div className="evidence-grid"><EvidencePanel title="Owner intelligence" description="Only legally available, source-backed owner fields appear here."><StateRow label="Owner name / entity type" /><StateRow label="Ownership duration" /><StateRow label="Estimated equity" /><StateRow label="Mortgage balance" /><StateRow label="Contact availability" value="No verified contact available" icon={ShieldCheck} /></EvidencePanel><EvidencePanel title="History & motivation evidence" description="Every signal retains its evidence, source, confidence, and timestamp."><StateRow label="Sales history" icon={SearchCheck} /><StateRow label="Listing history" icon={SearchCheck} /><StateRow label="Motivation signals" icon={Target} /><StateRow label="Last provider update" value="Not retrieved" icon={AlertCircle} /></EvidencePanel><EvidencePanel title="Motivation signal review" description="Deterministic signals are surfaced without turning unknown values into assumptions."><div className="signal-grid"><div><strong>Evidence</strong><span>HIGH_EQUITY · LONG_OWNERSHIP · LONG_DOM</span></div><div><strong>Confidence</strong><span>CONFIGURATION REQUIRED</span></div><div><strong>Suggested strategy</strong><span>CONFIGURATION REQUIRED</span></div></div><EmptyEvidence title="No signals evaluated" description="The backend returns an empty signal list when owner and property evidence is unavailable." /></EvidencePanel></div>;
}
function CompDetails() {
  return <EvidencePanel title="Comparable quality review" description="Selection reason, exclusion reason, score breakdown, and audit state stay visible together."><div className="quality-header"><span>Comparable</span><span>Distance</span><span>Recency</span><span>Similarity</span><span>Quality</span><span>Decision</span></div><div className="quality-empty"><Scale size={18}/><strong>No comparable sales loaded</strong><span>Qualified records will show score factors from 0–1, weighted contribution, MAD outlier status, and the reason for inclusion or exclusion.</span></div><div className="evidence-action-row"><button type="button" className="button button-secondary" disabled><SlidersHorizontal size={14}/> Adjust selection controls</button><button type="button" className="button button-secondary" disabled><CheckCircle2 size={14}/> Recalculate ARV</button><span><LockKeyhole size={14}/> Override requires a reason and audit event</span></div></EvidencePanel>;
}
function DealDetails() {
  return <div className="evidence-grid"><EvidencePanel title="Deterministic deal analysis" description="Server-calculated values, visible formulas, and retained data classifications."><div className="evidence-stats metric-stats"><SectionStat label="ARV" detail="Weighted qualified comparables" /><SectionStat label="Repairs" detail="Condition formula / user override" /><SectionStat label="MAO" detail="ARV − repairs − holding − profit" /><SectionStat label="Wholesale spread" detail="Assignment price − contract price" /><SectionStat label="Wholesale margin" detail="Spread ÷ contract price" /><SectionStat label="Flip profit" detail="Sale price − explicit costs" /><SectionStat label="ROI" detail="Net profit ÷ invested capital" /><SectionStat label="Deal score / risk" detail="Configured weighted factors" /></div></EvidencePanel><EvidencePanel title="Calculation assumptions" description="No hidden assumptions are applied when the engine configuration is undefined."><StateRow label="ARV confidence" value="CONFIGURATION REQUIRED" /><StateRow label="Holding costs" /><StateRow label="Profit margin" /><StateRow label="Financing costs" /><StateRow label="Analysis snapshot" value="Created only at validated Under Contract transition" /></EvidencePanel><EvidencePanel title="Activity timeline" description="Append-only events establish user, timestamp, action, and before/after context."><EmptyEvidence title="No deal activity" description="Stage changes, offer rounds, overrides, snapshot creation, and buyer responses will appear in chronological order." /></EvidencePanel></div>;
}
function SellerDetails() {
  return <div className="evidence-grid"><EvidencePanel title="Outreach history" description="Email, phone, mail, and future SMS attempts remain auditable."><EmptyEvidence title="No outreach attempts" description="Sent, opened, responded, and no-answer states are stored only after a verified contact and user action." /></EvidencePanel><EvidencePanel title="Follow-up tasks" description="Due dates, notes, completion, and reschedule reasons."><EmptyEvidence title="No follow-up tasks" description="Schedule a follow-up after a reviewed message or logged seller interaction." /></EvidencePanel><EvidencePanel title="Offers & negotiation" description="Draft, sent, countered, accepted, rejected, expired, and withdrawn states."><StateRow label="Current offer" /><StateRow label="Seller counteroffer" /><StateRow label="Negotiation status" value="NOT STARTED" icon={MessageSquareText} /></EvidencePanel></div>;
}
function BuyerDetails() {
  return <div className="evidence-grid"><EvidencePanel title="Deterministic match factors" description="Ranked results show matched and failed criteria—not opaque AI ranking."><div className="quality-header"><span>Buyer</span><span>Score</span><span>Market</span><span>ZIP</span><span>Price / ARV</span><span>Spread</span></div><div className="quality-empty"><UsersRound size={18}/><strong>No buyer matches</strong><span>Under-contract inputs and structured acquisition criteria are required before ranking can run.</span></div></EvidencePanel><EvidencePanel title="Interest & offer tracking" description="Buyer responses and offers remain tied to the distribution event."><StateRow label="Interest status" /><StateRow label="Offer amount" /><StateRow label="Financing" /><StateRow label="Response timestamp" /></EvidencePanel><EvidencePanel title="Shortlist explanation" description="Criteria evaluation is retained for each candidate."><div className="indicator-grid"><div><strong>Matched criteria</strong><span>—</span><small>Market, ZIP, type, price, ARV, spread, finance, activity</small></div><div><strong>Failed criteria</strong><span>—</span><small>Visible when a buyer does not qualify</small></div><div><strong>Confidence</strong><span>—</span><small>Depends on completeness of buyer and deal data</small></div></div></EvidencePanel></div>;
}
function ContractDetails() {
  return <div className="evidence-grid"><EvidencePanel title="Offer comparison" description="Side-by-side offers show price, closing date, contingencies, financing, and deterministic deal context."><div className="quality-header"><span>Buyer</span><span>Offer</span><span>Closing</span><span>Terms</span><span>Status</span></div><EmptyEvidence title="No buyer offers" description="Offers received through a distribution event appear here for comparison and selection." /></EvidencePanel><EvidencePanel title="Buyer selection & assignment" description="Selection and assignment actions create auditable events and versioned documents."><StateRow label="Selected buyer" /><StateRow label="Assignment fee" /><StateRow label="Assignment document" value="NO VERSION CREATED" icon={FileCheck2} /><StateRow label="Selection audit event" value="PENDING" /></EvidencePanel><EvidencePanel title="Closing outcome" description="Record the verified closing price, date, costs, and final net outcome."><StateRow label="Closing date" /><StateRow label="Closing price" /><StateRow label="Closing costs" /><StateRow label="Final net" /><div className="evidence-action-row"><button type="button" className="button button-secondary" disabled>Record verified closing</button></div></EvidencePanel></div>;
}
function SettingsDetails() {
  return <div className="evidence-grid"><EvidencePanel title="Standalone activation state" description="Live integrations are disabled by user request; these are activation boundaries, not data claims."><StateRow label="Property data" value="DISABLED BY REQUEST" /><StateRow label="Authentication" value="DISABLED BY REQUEST" /><StateRow label="Persistence" value="DISABLED BY REQUEST" /><StateRow label="AI drafting" value="DISABLED BY REQUEST" /><StateRow label="Document storage" value="DISABLED BY REQUEST" /></EvidencePanel><EvidencePanel title="Plan and usage contract" description="The product is ready to read approved entitlements when billing is configured."><StateRow label="Current plan" value="NOT CONFIGURED" /><StateRow label="Search usage" value="NOT METERED" /><StateRow label="Analysis usage" value="NOT METERED" /><StateRow label="Billing status" value="NOT ACTIVE" /></EvidencePanel></div>;
}

export function StandaloneWorkflowDetails({ mode }: { mode: Mode }) {
  const content = { search: <SearchDetails />, properties: <PropertyDetails />, deals: <DealDetails />, sellers: <SellerDetails />, buyers: <BuyerDetails />, contracts: <ContractDetails />, settings: <SettingsDetails /> }[mode];
  return <section className="standalone-evidence"><div className="standalone-heading"><div><p className="eyebrow">Operational detail layer</p><h2>Evidence-first workflow controls</h2><p>These panels are ready for provider-backed records and remain explicit when the standalone preview has no live source.</p></div><span className="standalone-chip"><Sparkles size={13}/> No AI data substitution</span></div>{content}</section>;
}
